---
title: "Treatment Discontinuation"
format:
  docx:
    reference-doc: template.docx
    fig-cap-location: top
execute:
  echo: false
  message: false
  warning: false
lof: true
---

```{r}
# Load necessary packages ----
library(OmopSketch)
library(visOmopResults)

# Load results stored in the package ----
fileData <- file.path(getwd(), "data", "studyData.RData")
if (!file.exists(fileData)) {
  source(file.path(getwd(), "rawData", "preprocess.R"))
}

# uncomment to load the raw data
# rawData <- omopgenerics::importSummarisedResult(file.path(getwd(), "rawData"))

# load data
load(fileData)

# source functions
source(file.path(getwd(), "functions.R"))

# Global options ----
knitr::opts_chunk$set(
  out.width  = "95%",  # figures occupy ~95% of document width
  out.height = "auto",
  dpi        = 320,    # ensure figure quality
  fig.width  = 6,      # default aspect ratio (can be overridden per-figure)
  fig.height = 3,
  results    = "asis"  # enable Markdown produced via cat() inside chunks
)

setGlobalPlotOptions(type = "ggplot")
setGlobalTableOptions(type = "flextable")

# Calibri font in ggplot figures (requires the extrafont package to be available)
# Read vignette on styles to learn more
requireExtrafont()
```

## Database metadata

:::{custom-style="Caption"}
**Table 1:** Database metadata.
:::

```{r}
OmopSketch::tableOmopSnapshot(data[["summarise_omop_snapshot"]])
```
