# Generated by OmopViewer 0.7.0
# Be careful editing this file

server <- function(input, output, session) {
  # download raw data -----
  output$download_raw <- shiny::downloadHandler(
    filename = "results.csv",
    content = function(file) {
      data |>
        omopgenerics::bind() |>
        omopgenerics::exportSummarisedResult(
          fileName = file, logFile = NULL, logSqlPath = NULL
        )
    }
  )

  # summarise_omop_snapshot -----
  ## get summarise_omop_snapshot data
  getSummariseOmopSnapshotData <- shiny::reactive({
    data[["summarise_omop_snapshot"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_omop_snapshot_cdm_name,
        .data$variable_name %in% input$summarise_omop_snapshot_variable_name
      )
  })
  getSummariseOmopSnapshotTable <- shiny::reactive({
    getSummariseOmopSnapshotData() |>
      OmopSketch::tableOmopSnapshot(
        header = input$summarise_omop_snapshot_table_header,
        groupColumn = input$summarise_omop_snapshot_table_group_column,
        hide = input$summarise_omop_snapshot_table_hide
      )
  })
  output$summarise_omop_snapshot_table <- gt::render_gt({
    getSummariseOmopSnapshotTable()
  })
  output$summarise_omop_snapshot_table_download <- shiny::downloadHandler(
    filename = paste0("table_snapshot.", input$summarise_omop_snapshot_table_format),
    content = function(file) {
      gt::gtsave(getSummariseOmopSnapshotTable(), file)
    }
  )

  # summarise_observation_period -----
  ## get summarise_observation_period data
  getSummariseObservationPeriodData <- shiny::reactive({
    data[["summarise_observation_period"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_observation_period_cdm_name,
        .data$variable_name %in% input$summarise_observation_period_variable_name,
        .data$estimate_name %in% input$summarise_observation_period_estimate_name
      ) |>
      omopgenerics::filterGroup(.data$observation_period_ordinal == "all")
  })
  getSummariseObservationPeriodTable <- shiny::reactive({
    getSummariseObservationPeriodData() |>
      OmopSketch::tableObservationPeriod(
        header = input$summarise_observation_period_table_header,
        groupColumn = input$summarise_observation_period_table_group_column,
        hide = input$summarise_observation_period_table_hide
      )
  })
  output$summarise_observation_period_table <- gt::render_gt({
    getSummariseObservationPeriodTable()
  })
  output$summarise_observation_period_table_download <- shiny::downloadHandler(
    filename = paste0("table_obsevation_period.", input$summarise_observation_period_table_format),
    content = function(file) {
      gt::gtsave(getSummariseObservationPeriodTable(), file)
    }
  )
  getSummariseObservationPeriodPlot <- shiny::reactive({
    getSummariseObservationPeriodData() |>
      OmopSketch::plotObservationPeriod(
        variableName = input$summarise_observation_period_plot_variable,
        plotType = input$summarise_observation_period_plot_plot_type,
        facet = input$summarise_observation_period_plot_facet,
        colour = input$summarise_observation_period_plot_colour
      )
  })
  output$summarise_observation_period_plot <- shiny::renderUI({
    x <- getSummariseObservationPeriodPlot()
    renderInteractivePlot(x, input$summarise_observation_period_plot_interactive)
  })
  output$summarise_observation_period_plot_download <- shiny::downloadHandler(
    filename = "plot_observation_period.png",
    content = function(file) {
      ggplot2::ggsave(
        filename = file,
        plot = getSummariseObservationPeriodPlot(),
        width = as.numeric(input$summarise_observation_period_plot_width),
        height = as.numeric(input$summarise_observation_period_plot_height),
        units = input$summarise_observation_period_plot_units,
        dpi = as.numeric(input$summarise_observation_period_plot_dpi)
      )
    }
  )

  # code_use -----
  ## get code_use data
  getCodeUseData <- shiny::reactive({
    data[["code_use"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$code_use_cdm_name,
        .data$estimate_name %in% input$code_use_estimate_name
      ) |>
      omopgenerics::filterGroup(.data$codelist_name %in% input$code_use_codelist_name) |>
      omopgenerics::filterAdditional(
        .data$type_concept_id %in% input$code_use_type_concept_id,
        .data$type_concept_name %in% input$code_use_type_concept_name,
        .data$domain_id %in% input$code_use_domain_id,
        .data$table %in% input$code_use_table
      )
  })
  getCodeUseTableReact <- shiny::reactive({
    getCodeUseData() |>
      CodelistGenerator::tableCodeUse(
        type = "reactable",
        header = "cdm_name"
      )
  })
  output$code_use_table_react <- reactable::renderReactable({
    getCodeUseTableReact()
  })
  getCodeUseTableGt <- shiny::reactive({
    getCodeUseData() |>
      CodelistGenerator::tableCodeUse(
        header = input$code_use_table_gt_header,
        groupColumn = input$code_use_table_gt_group_column,
        hide = input$code_use_table_gt_hide
      )
  })
  output$code_use_table_gt <- gt::render_gt({
    getCodeUseTableGt()
  })
  output$code_use_table_gt_download <- shiny::downloadHandler(
    filename = paste0("table_code_use.", input$code_use_table_gt_format),
    content = function(file) {
      gt::gtsave(getCodeUseTableGt(), file)
    }
  )

  # summarise_cohort_count -----
  ## get summarise_cohort_count data
  getSummariseCohortCountData <- shiny::reactive({
    data[["summarise_cohort_count"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_cohort_count_cdm_name,
        .data$variable_name %in% input$summarise_cohort_count_variable_name
      ) |>
      omopgenerics::filterGroup(.data$cohort_name %in% input$summarise_cohort_count_cohort_name)
  })
  getSummariseCohortCountTable <- shiny::reactive({
    getSummariseCohortCountData() |>
      CohortCharacteristics::tableCohortCount(
        header = input$summarise_cohort_count_table_header,
        groupColumn = input$summarise_cohort_count_table_group_column,
        hide = input$summarise_cohort_count_table_hide
      )
  })
  output$summarise_cohort_count_table <- gt::render_gt({
    getSummariseCohortCountTable()
  })
  output$summarise_cohort_count_table_download <- shiny::downloadHandler(
    filename = paste0("table_count.", input$summarise_cohort_count_table_format),
    content = function(file) {
      gt::gtsave(getSummariseCohortCountTable(), file)
    }
  )
  getSummariseCohortCountPlot <- shiny::reactive({
    getSummariseCohortCountData() |>
      CohortCharacteristics::plotCohortCount(
        facet = input$summarise_cohort_count_plot_facet,
        colour = input$summarise_cohort_count_plot_colour
      )
  })
  output$summarise_cohort_count_plot <- shiny::renderUI({
    x <- getSummariseCohortCountPlot()
    renderInteractivePlot(x, input$summarise_cohort_count_plot_interactive)
  })
  output$summarise_cohort_count_plot_download <- shiny::downloadHandler(
    filename = "plot_count.png",
    content = function(file) {
      ggplot2::ggsave(
        filename = file,
        plot = getSummariseCohortCountPlot(),
        width = as.numeric(input$summarise_cohort_count_plot_width),
        height = as.numeric(input$summarise_cohort_count_plot_height),
        units = input$summarise_cohort_count_plot_units,
        dpi = as.numeric(input$summarise_cohort_count_plot_dpi)
      )
    }
  )

  # summarise_cohort_attrition -----
  ## get summarise_cohort_attrition data
  getSummariseCohortAttritionData <- shiny::reactive({
    data[["summarise_cohort_attrition"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_cohort_attrition_cdm_name,
        .data$variable_name %in% input$summarise_cohort_attrition_variable_name
      ) |>
      omopgenerics::filterGroup(.data$cohort_name %in% input$summarise_cohort_attrition_cohort_name)
  })
  getSummariseCohortAttritionTable <- shiny::reactive({
    getSummariseCohortAttritionData() |>
      CohortCharacteristics::tableCohortAttrition(
        header = input$summarise_cohort_attrition_table_header,
        groupColumn = input$summarise_cohort_attrition_table_group_column,
        hide = input$summarise_cohort_attrition_table_hide
      )
  })
  output$summarise_cohort_attrition_table <- gt::render_gt({
    getSummariseCohortAttritionTable()
  })
  output$summarise_cohort_attrition_table_download <- shiny::downloadHandler(
    filename = paste0("table_attrition.", input$summarise_cohort_attrition_table_format),
    content = function(file) {
      gt::gtsave(getSummariseCohortAttritionTable(), file)
    }
  )
  getSummariseCohortAttritionDiagram <- shiny::reactive({
    getSummariseCohortAttritionData() |>
      CohortCharacteristics::plotCohortAttrition(
        show = input$summarise_cohort_attrition_diagram_show
      )
  })
  output$summarise_cohort_attrition_diagram <- DiagrammeR::renderGrViz({
    getSummariseCohortAttritionDiagram()
  })
  output$summarise_cohort_attrition_diagram_download <- shiny::downloadHandler(
    filename = "attrition_diagram.png",
    content = function(file) {
      svg <- DiagrammeRsvg::export_svg(getSummariseCohortAttritionDiagram())
      rsvg::rsvg_png(charToRaw(svg), file, width = input$summarise_cohort_attrition_diagram_width)
    }
  )

  # summarise_characteristics -----
  ## get summarise_characteristics data
  getSummariseCharacteristicsData <- shiny::reactive({
    data[["summarise_characteristics"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_characteristics_cdm_name,
        .data$variable_name %in% input$summarise_characteristics_variable_name,
        .data$estimate_name %in% input$summarise_characteristics_estimate_name
      ) |>
      omopgenerics::filterGroup(.data$cohort_name %in% input$summarise_characteristics_cohort_name) |>
      omopgenerics::filterStrata(.data$prior_heart_failure %in% input$summarise_characteristics_prior_heart_failure)
  })
  getSummariseCharacteristicsTable <- shiny::reactive({
    getSummariseCharacteristicsData() |>
      CohortCharacteristics::tableCharacteristics(
        header = input$summarise_characteristics_table_header,
        groupColumn = input$summarise_characteristics_table_group_column,
        hide = input$summarise_characteristics_table_hide
      )
  })
  output$summarise_characteristics_table <- gt::render_gt({
    getSummariseCharacteristicsTable()
  })
  output$summarise_characteristics_table_download <- shiny::downloadHandler(
    filename = paste0("table_characteristics.", input$summarise_characteristics_table_format),
    content = function(file) {
      gt::gtsave(getSummariseCharacteristicsTable(), file)
    }
  )
  getSummariseCharacteristicsPlot <- shiny::reactive({
    getSummariseCharacteristicsData() |>
      CohortCharacteristics::plotCharacteristics(
        plotType = input$summarise_characteristics_plot_plot_type,
        facet = input$summarise_characteristics_plot_facet,
        colour = input$summarise_characteristics_plot_colour
      )
  })
  output$summarise_characteristics_plot <- shiny::renderUI({
    x <- getSummariseCharacteristicsPlot()
    renderInteractivePlot(x, input$summarise_characteristics_plot_interactive)
  })
  output$summarise_characteristics_plot_download <- shiny::downloadHandler(
    filename = "plot_characteristics.png",
    content = function(file) {
      ggplot2::ggsave(
        filename = file,
        plot = getSummariseCharacteristicsPlot(),
        width = as.numeric(input$summarise_characteristics_plot_width),
        height = as.numeric(input$summarise_characteristics_plot_height),
        units = input$summarise_characteristics_plot_units,
        dpi = as.numeric(input$summarise_characteristics_plot_dpi)
      )
    }
  )

  # summarise_proportion_of_patients_covered -----
  ## get summarise_proportion_of_patients_covered data
  getSummariseProportionOfPatientsCoveredData <- shiny::reactive({
    data[["summarise_proportion_of_patients_covered"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_proportion_of_patients_covered_cdm_name,
        .data$estimate_name %in% input$summarise_proportion_of_patients_covered_estimate_name
      ) |>
      omopgenerics::filterGroup(.data$cohort_name %in% input$summarise_proportion_of_patients_covered_cohort_name) |>
      omopgenerics::filterStrata(.data$prior_heart_failure %in% input$summarise_proportion_of_patients_covered_prior_heart_failure)
  })
  getSummariseProportionOfPatientsCoveredTable <- shiny::reactive({
    getSummariseProportionOfPatientsCoveredData() |>
      DrugUtilisation::tableProportionOfPatientsCovered(
        header = input$summarise_proportion_of_patients_covered_table_header,
        groupColumn = input$summarise_proportion_of_patients_covered_table_group_column,
        hide = input$summarise_proportion_of_patients_covered_table_hide
      )
  })
  output$summarise_proportion_of_patients_covered_table <- gt::render_gt({
    getSummariseProportionOfPatientsCoveredTable()
  })
  output$summarise_proportion_of_patients_covered_table_download <- shiny::downloadHandler(
    filename = paste0("table_ppc.", input$summarise_proportion_of_patients_covered_table_format),
    content = function(file) {
      gt::gtsave(getSummariseProportionOfPatientsCoveredTable(), file)
    }
  )
  getSummariseProportionOfPatientsCoveredPlot <- shiny::reactive({
    getSummariseProportionOfPatientsCoveredData() |>
      DrugUtilisation::plotProportionOfPatientsCovered(
        ribbon = input$summarise_proportion_of_patients_covered_plot_ribbon,
        facet = input$summarise_proportion_of_patients_covered_plot_facet,
        colour = input$summarise_proportion_of_patients_covered_plot_colour
      )
  })
  output$summarise_proportion_of_patients_covered_plot <- shiny::renderUI({
    x <- getSummariseProportionOfPatientsCoveredPlot()
    renderInteractivePlot(x, input$summarise_proportion_of_patients_covered_plot_interactive)
  })
  output$summarise_proportion_of_patients_covered_plot_download <- shiny::downloadHandler(
    filename = "plot_ppc.png",
    content = function(file) {
      ggplot2::ggsave(
        filename = file,
        plot = getSummariseProportionOfPatientsCoveredPlot(),
        width = as.numeric(input$summarise_proportion_of_patients_covered_plot_width),
        height = as.numeric(input$summarise_proportion_of_patients_covered_plot_height),
        units = input$summarise_proportion_of_patients_covered_plot_units,
        dpi = as.numeric(input$summarise_proportion_of_patients_covered_plot_dpi)
      )
    }
  )

  # summarise_log_file -----
  output$summarise_log_file_table <- gt::render_gt({
    data$summarise_log_file |>
      dplyr::filter(.data$estimate_name == "date_time") |>
      visOmopResults::visOmopTable(
        header = "cdm_name",
        hide = c("variable_level", "estimate_name")
      )
  })
  output$summarise_log_file_plot <- shiny::renderPlot({
    x <- data$summarise_log_file |>
      dplyr::filter(.data$estimate_name == "elapsed_time") |>
      omopgenerics::tidy() |>
      dplyr::mutate(variable_name = sprintf("%02i - %s", as.integer(log_id), variable_name))
    ggplot2::ggplot(data = x, mapping = ggplot2::aes(x = variable_name, y = elapsed_time, fill = cdm_name)) +
      ggplot2::geom_col(position = "dodge") +
      ggplot2::geom_text(
        mapping = ggplot2::aes(label = round(elapsed_time, 1)),
        position = ggplot2::position_dodge2(width = 0.9),
        vjust = -0.3,
        size = 3
      ) +
      visOmopResults::themeVisOmop() +
      ggplot2::theme(
        legend.position = "top",
        axis.text.x = ggplot2::element_text(angle = 60, hjust = 1)
      ) +
      ggplot2::labs(x = "Task", y = "Time (seconds)")
  }, height = 700)

  # summarise_multistate_probabilities -----
  ## get summarise_multistate_probabilities data
  getSummariseMultistateProbabilitiesData <- shiny::reactive({
    data[["summarise_multistate_probabilities"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_multistate_probabilities_cdm_name,
        .data$variable_name %in% input$summarise_multistate_probabilities_variable_name,
        .data$estimate_name %in% input$summarise_multistate_probabilities_estimate_name
      ) |>
      omopgenerics::filterGroup(.data$initial_state %in% input$summarise_multistate_probabilities_initial_state) |>
      omopgenerics::filterStrata(.data$prior_heart_failure %in% input$summarise_multistate_probabilities_prior_heart_failure) |>
      omopgenerics::filterSettings(.data$state_hierarchy %in% input$summarise_multistate_probabilities_state_hierarchy)
  })
  getSummariseMultistateProbabilitiesTidy <- shiny::reactive({
    tidyDT(getSummariseMultistateProbabilitiesData(), input$summarise_multistate_probabilities_tidy_columns, input$summarise_multistate_probabilities_tidy_pivot_estimates)
  })
  output$summarise_multistate_probabilities_tidy <- DT::renderDT({
    getSummariseMultistateProbabilitiesTidy()
  })
  output$summarise_multistate_probabilities_tidy_download <- shiny::downloadHandler(
    filename = "tidy_results.csv",
    content = function(file) {
      getSummariseMultistateProbabilitiesData() |>
        omopgenerics::tidy() |>
        readr::write_csv(file = file)
    }
  )
  getSummariseMultistateProbabilitiesTable <- shiny::reactive({
    getSummariseMultistateProbabilitiesData() |>
      simpleTable(
        header = input$summarise_multistate_probabilities_table_header,
        group = input$summarise_multistate_probabilities_table_group_column,
        hide = input$summarise_multistate_probabilities_table_hide
      )
  })
  output$summarise_multistate_probabilities_table <- gt::render_gt({
    getSummariseMultistateProbabilitiesTable()
  })
  output$summarise_multistate_probabilities_table_download <- shiny::downloadHandler(
    filename = paste0("table.", input$summarise_multistate_probabilities_table_format),
    content = function(file) {
      gt::gtsave(getSummariseMultistateProbabilitiesTable(), file)
    }
  )

  # single_survival -----
  ## get single_survival data
  getSingleSurvivalData <- shiny::reactive({
    pt <- paste0(sprintf("%03i", as.integer(input$single_survival_gap)), collapse = "|")
    data[["single_survival"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$single_survival_cdm_name
      ) |>
      omopgenerics::filterGroup(stringr::str_ends(.data$cohort_name, pt)) |>
      omopgenerics::filterStrata(.data$prior_heart_failure %in% input$single_survival_prior_heart_failure)
  })
  output$single_summary <- gt::render_gt({
    getSingleSurvivalData() |>
      DrugUtilisation::tableDiscontinuationAsSurvival(
        groupColumn = "cohort_name",
        header = c("cdm_name", "prior_heart_failure"),
        hide = c("variable_level", "variable_name", "competing_outcome", "estimate_gap",
            "event_gap", "follow_up_days", "cohort_survival_version"),
        gapSummary = FALSE
      )
  })
  output$single_events <- gt::render_gt({
    getSingleSurvivalData() |>
      filter(stringr::str_starts(.data$variable_name, "Gap")) |>
      DrugUtilisation::tableDiscontinuationAsSurvival(
        groupColumn = "cohort_name",
        header = c("cdm_name", "prior_heart_failure"),
        hide = c("variable_name", "competing_outcome", "estimate_gap",
                 "event_gap", "follow_up_days", "cohort_survival_version")
      )
  })
  output$single_probbaility <- reactable::renderReactable({
    getSingleSurvivalData() |>
      filter(stringr::str_starts(.data$variable_name, "Survival")) |>
      omopgenerics::tidy() |>
      dplyr::mutate(variable_name = "Survival probability") |>
      dplyr::rename("time" = "variable_level") |>
      dplyr::select(!c(
        "cohort_survival_version", "competing_outcome", "estimate_gap",
        "event_gap", "follow_up_days"
      )) |>
      reactable::reactable(sortable = TRUE, filterable = TRUE, defaultPageSize = 20)
  })
  output$single_plot <- shiny::renderPlot({
    if (input$single_compare == "gaps") {
      facet <- "prior_heart_failure"
      colour <- "cohort_name"
    } else {
      colour <- "prior_heart_failure"
      facet <- "cohort_name"
    }
    getSingleSurvivalData() |>
      DrugUtilisation::plotDiscontinuationAsSurvival(
        facet = facet,
        colour = colour
      ) +
      ggplot2::theme(legend.position = "top")
  })

  # competing_survival -----
  ## get competing_survival data
  getCompetingSurvivalData <- shiny::reactive({
    data[["competing_survival"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$competing_survival_cdm_name,
        .data$variable_name %in% input$competing_survival_variable_name,
        .data$estimate_name %in% input$competing_survival_estimate_name
      ) |>
      omopgenerics::filterGroup(.data$cohort_name %in% input$competing_survival_cohort_name) |>
      omopgenerics::filterStrata(.data$prior_heart_failure %in% input$competing_survival_prior_heart_failure)
  })
  getCompetingSurvivalTidy <- shiny::reactive({
    tidyDT(getCompetingSurvivalData(), input$competing_survival_tidy_columns, input$competing_survival_tidy_pivot_estimates)
  })
  output$competing_survival_tidy <- DT::renderDT({
    getCompetingSurvivalTidy()
  })
  output$competing_survival_tidy_download <- shiny::downloadHandler(
    filename = "tidy_results.csv",
    content = function(file) {
      getCompetingSurvivalData() |>
        omopgenerics::tidy() |>
        readr::write_csv(file = file)
    }
  )
  getCompetingSurvivalTable <- shiny::reactive({
    getCompetingSurvivalData() |>
      simpleTable(
        header = input$competing_survival_table_header,
        group = input$competing_survival_table_group_column,
        hide = input$competing_survival_table_hide
      )
  })
  output$competing_survival_table <- gt::render_gt({
    getCompetingSurvivalTable()
  })
  output$competing_survival_table_download <- shiny::downloadHandler(
    filename = paste0("table.", input$competing_survival_table_format),
    content = function(file) {
      gt::gtsave(getCompetingSurvivalTable(), file)
    }
  )

  # discontinuation -----
  ## get discontinuation data
  getDiscontinuationData <- shiny::reactive({
    data[["discontinuation"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$discontinuation_cdm_name,
        .data$gap %in% input$discontinuation_gap,
        .data$method %in% input$discontinuation_method
      )
  })
  output$discontinuation_explore <- reactable::renderReactable({
    getDiscontinuationData() |>
      reactable::reactable(filterable = TRUE)
  })
  
}
